name: portfolio
description: My portfolio.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - web/assets/images/personal_photo.jpg
    - web/assets/images/github.png
    - web/assets/images/test_pic.png
#   fonts:
