name: portfolio
description: My portfolio.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  
  provider: ^4.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/personal_photo.jpg
    - assets/images/test/

    - assets/images/fly_food/
    - assets/images/u_turn/

  fonts:
    - family: Rowdies
      fonts:
        - asset: assets/fonts/Rowdies-Light.ttf
          weight: 300
        - asset: assets/fonts/Rowdies-Regular.ttf
        - asset: assets/fonts/Rowdies-Bold.ttf
          weight: 700

    - family: GochiHand
      fonts:
        - asset: assets/fonts/GochiHand-Regular.ttf
